# Generated by Django 5.1.3 on 2026-07-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField()),
                ('entidad_afectada', models.TextField()),
                ('id_registro_afectado', models.IntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('ip_origen', models.TextField(blank=True, null=True)),
                ('navegador', models.TextField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Log_Auditoria',
            },
        ),
    ]
