# Generated by Django 5.1.3 on 2026-07-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.TextField()),
                ('monto', models.FloatField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], max_length=10)),
            ],
            options={
                'db_table': 'Cuota_Mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('fecha_pago', models.DateField()),
                ('numero_operacion', models.TextField(blank=True, null=True)),
                ('comprobante_url', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=10)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('observacion_validacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Pago',
            },
        ),
    ]
