# Generated by Django 5.1.3 on 2026-07-11 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotamantenimiento',
            name='id_residente',
            field=models.ForeignKey(db_column='id_residente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.residente'),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_admin_validador',
            field=models.ForeignKey(blank=True, db_column='id_admin_validador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.administrador'),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_cuota',
            field=models.ForeignKey(db_column='id_cuota', on_delete=django.db.models.deletion.CASCADE, to='pagos.cuotamantenimiento'),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_residente',
            field=models.ForeignKey(db_column='id_residente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.residente'),
        ),
    ]
