# Generated by Django 5.1.3 on 2026-07-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comprobante_url',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
