# Generated by Django 5.1.3 on 2026-07-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('informativo', 'Informativo'), ('urgente', 'Urgente'), ('recordatorio', 'Recordatorio')], max_length=15)),
            ],
            options={
                'db_table': 'Comunicacion',
            },
        ),
        migrations.CreateModel(
            name='ComunicacionDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Comunicacion_Destinatario',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('archivo_url', models.TextField()),
                ('fecha_publicacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Documento',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField()),
                ('url_accion', models.TextField(blank=True, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Notificacion',
            },
        ),
    ]
