# Generated by Django 5.1.3 on 2026-07-11 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunicaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicacion',
            name='id_admin_remitente',
            field=models.ForeignKey(db_column='id_admin_remitente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.administrador'),
        ),
        migrations.AddField(
            model_name='comunicaciondestinatario',
            name='id_comunicacion',
            field=models.ForeignKey(db_column='id_comunicacion', on_delete=django.db.models.deletion.CASCADE, to='comunicaciones.comunicacion'),
        ),
        migrations.AddField(
            model_name='comunicaciondestinatario',
            name='id_residente',
            field=models.ForeignKey(db_column='id_residente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.residente'),
        ),
        migrations.AddField(
            model_name='documento',
            name='id_administrador',
            field=models.ForeignKey(db_column='id_administrador', on_delete=django.db.models.deletion.CASCADE, to='usuarios.administrador'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='id_comunicacion',
            field=models.ForeignKey(blank=True, db_column='id_comunicacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comunicaciones.comunicacion'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='id_residente',
            field=models.ForeignKey(db_column='id_residente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.residente'),
        ),
    ]
