# Generated by Django 5.1.3 on 2026-07-11 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('nombre', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('residente', 'Residente'), ('administrador', 'Administrador')], max_length=20)),
                ('nacionalidad', models.CharField(choices=[('peruana', 'Peruana'), ('extranjero', 'Extranjero')], default='peruana', max_length=20)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('Carnet de Extranjería', 'Carnet de Extranjería')], max_length=30)),
                ('numero_documento', models.TextField(unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.TextField()),
                ('permisos', models.TextField(blank=True, null=True)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(unique=True)),
                ('dpto_destino', models.TextField()),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_admin_creador', models.ForeignKey(db_column='id_admin_creador', on_delete=django.db.models.deletion.CASCADE, to='usuarios.administrador')),
            ],
            options={
                'db_table': 'Invitacion',
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_departamento', models.TextField()),
                ('estado_financiero', models.CharField(choices=[('al_dia', 'Al día'), ('moroso', 'Moroso')], max_length=10)),
                ('fecha_ingreso', models.DateField()),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Residente',
            },
        ),
        migrations.CreateModel(
            name='SolicitudRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('dpto_solicitado', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('id_admin_procesa', models.ForeignKey(blank=True, db_column='id_admin_procesa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.administrador')),
            ],
            options={
                'db_table': 'Solicitud_Registro',
            },
        ),
    ]
