# Generated by Django 5.1.3 on 2026-07-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('seguridad', 'Seguridad'), ('servicios', 'Servicios'), ('otros', 'Otros')], max_length=15)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=5)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('asignado', 'Asignado'), ('en_progreso', 'En Progreso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], max_length=15)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('evidencia_url', models.TextField(blank=True, null=True)),
                ('clasificacion_ia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Incidencia',
            },
        ),
        migrations.CreateModel(
            name='IncidenciaSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('estado_anterior', models.TextField()),
                ('estado_nuevo', models.TextField()),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'Incidencia_Seguimiento',
            },
        ),
    ]
