# Generated by Django 5.1.3 on 2026-07-11 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidencias', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='id_admin_asignado',
            field=models.ForeignKey(blank=True, db_column='id_admin_asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.administrador'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='id_residente',
            field=models.ForeignKey(db_column='id_residente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.residente'),
        ),
        migrations.AddField(
            model_name='incidenciaseguimiento',
            name='id_incidencia',
            field=models.ForeignKey(db_column='id_incidencia', on_delete=django.db.models.deletion.CASCADE, to='incidencias.incidencia'),
        ),
        migrations.AddField(
            model_name='incidenciaseguimiento',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
