# Generated by Django 5.1.3 on 2026-07-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidencias", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incidencia",
            name="evidencia_url",
        ),
        migrations.AddField(
            model_name="incidencia",
            name="evidencia",
            field=models.FileField(blank=True, null=True, upload_to="evidencias/"),
        ),
    ]
