# Generated by Django 5.1.3 on 2026-07-11 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='id_residente',
            field=models.ForeignKey(db_column='id_residente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.residente'),
        ),
    ]
